### ISSUE TITLE
Take down Riverside Fixit+

### ISSUE THREAD

**Issue by ekemeyer** [WGBH-MLA/transcript-editor#182]
We no longer need to maintain the Riverside instance of Fixit+, however we do need to move those transcripts into fixit+.

```[tasklist]
### Tasks
- [x] Push transcripts from https://wrvrtranscripts.americanarchive.org/ to AAPB (see criteria in comment)
- [x] Pull back transcripts from AAPB to https://fixitplus.americanarchive.org/ (see criteria in later comment)
- [x] Take down https://wrvrtranscripts.americanarchive.org/
```

**Comment by ekemeyer** [comment]
List of wrvr guids in Fixit+ attached [wrvr_fixit+.txt](https://github.com/user-attachments/files/17526975/wrvr_fixit%2B.txt)

**Comment by ekemeyer** [comment]
Identified transcripts in WRVR FIXIT+ that need to be pushed based on whether or not they met at least 1 of the following criteria:
1. Completed
2. Had at least 1 contributor
3. Were not on the list provided by Kevin of recently whispered items (what is in Fixit+ came from Kaldi)

List of those attached - they will need to be pushed to AAPB from Fixit+

[ready_river_push_to_AAPB.txt](https://github.com/user-attachments/files/18679400/ready_river_push_to_AAPB.txt)

**Comment by ekemeyer** [comment]
Not all guids were in AMS2, so I could not update organization value and bring into Fixit+ (about 40)

**Comment by ekemeyer** [comment]
Terminated AWS instance, dissociated/released elastic IP address, volume automatically removed after terminating instance.
